version: "3.8"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "${PORT}:3000"
    environment:
      PORT: $PORT
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      JWT_SECRET: $JWT_SECRET
    depends_on:
      - mysql

volumes:
  mysql-data:
